# Generated by Django 4.2.6 on 2023-11-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_image', models.ImageField(upload_to='product_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=60)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=150)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.productimages')),
                ('gender', models.CharField(max_length=25)),
                ('master_category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('article_type', models.CharField(max_length=50)),
                ('base_color', models.CharField(max_length=40)),
                ('season', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('usage', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
